# -*- coding: utf-8 -*-
"""digit_recognition_cnn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18FVWvjyoZw-fLsUF_OsSEKla9bA_-vD0

# Digit Recognition CNN

**Colab Identification**
"""

from google.colab import drive
drive.mount('/content/drive/')

"""### Installations and Controls"""

from tensorflow.python.client import device_lib
device_lib.list_local_devices()

"""**Directory Operations**"""

!ls drive

import os 
os.chdir("/content/drive/MyDrive/Udemy_DerinOgrenmeyeGiris/Evrisimli_Sinir_Aglari/")
!pwd

!ls

!pip install -q keras

"""### Load Dependencies"""

from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import load_model
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras. layers import Conv2D, MaxPooling2D
from keras import backend as K

import matplotlib.pyplot as plt

"""### Load Dataset"""

(x_train, y_train), (x_test, y_test) = mnist.load_data()

"""### Visualization of dataset"""

plt.figure(figsize=(14,14))
x, y = 10, 4 
for i in range(40):  
    plt.subplot(y, x, i+1)
    plt.imshow(x_train[i])
plt.show()

batch_size = 128 
num_classes = 10 
epochs = 10

img_rows, img_cols = 28, 28

if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

# Label Encoding
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

"""## MODEL BUILDING"""

model = Sequential()

"""**Add Layers**"""

model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(num_classes, activation='softmax'))

"""Model Visualization

"""

model.summary()

# Compile the model
model.compile(loss = keras.losses.categorical_crossentropy,
             optimizer = keras.optimizers.Adadelta(),
             metrics = ['accuracy'])

"""### Training Operation"""

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))

# Save the model
model.save('save_models/mnist_model.h5')

score = model.evaluate(x_test, y_test, verbose=0)
print('Test Loss:', score[0])
print('Test Accuracy:', score[1])

"""**Make Prediction**"""

model_test = model.save('save_models/mnist_model.h5')

test_image = x_test[32]
y_test[32]

plt.imshow(test_image.reshape(28,28))

test_data = x_test[32].reshape(1,28,28,1)
pre=model_test.predict(test_data, batch_size=1)

